color0 #46464f
color1 #ffb4ab
color2 #bdc2ff
color3 #c5c4dd
color4 #e7b9d5
color5 #bdc2ff
color6 #c5c4dd
color7 #e4e1e9
color8 #91909a
color9 #ffb4ab
color10 #bdc2ff
color11 #c5c4dd
color12 #e7b9d5
color13 #bdc2ff
color14 #c5c4dd
color15 #e4e1e9

cursor                #e4e1e9
cursor_text_color     #131318
background            #131318
foreground            #e4e1e9
selection_foreground  #c7c5d0
selection_background  #46464f
active_border_color   #bdc2ff
inactive_border_color #46464f
url_color             #bdc2ff

active_tab_foreground   #262b61
active_tab_background   #bdc2ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #46464f
cursor_trail_color      #c7c5d0
