name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Run install.sh
      run: ${GITHUB_WORKSPACE}/bin/install.sh

    - name: Load .bash_profile
      run: |
        bash ~/.bash_profile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .bashrc
      run: |
        bash ~/.bashrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi