name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: info
      run: |
        echo "現在地:$(pwd)"
        echo "ホーム: $HOME"

    - name: Run dotfiles install script
      run: ${GITHUB_WORKSPACE}/setup.sh

    - name: file check
      run: |
        cd $HOME
        echo "現在地：$(pwd)"
        ls -al $HOME
        ls -al $HOME/.bin
        ls -al $HOME/.config
        cd # HOME に移動
        pwd 
        if [ -L $HOME/.bashrc ]; then
          echo "::notice::bashrcおるで"
        else
          echo "::error::bashrcおらんで"
          exit 1
        fi