name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Run install.sh
      run: ${GITHUB_WORKSPACE}/install.sh

    - name: step
      run: |
        pwd 
        ls -al

    - name: step2
      run: |
        cd #HOME に移動
        pwd 
        if [ -L $HOME/.bashrc ]; then
          echo "::notice::bashrcおるで"
        else
          echo "::error::bashrcおらんで"
          exit 1
        fi