name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Run install.sh
      run: ${GITHUB_WORKSPACE}/install.sh

    - name: Check if .bashrc exists in repository
      run: |
        # GitHub Actions のワークスペース内のパスを確認
        HOME_PATH="~/.bashrc"

        if [ -f "$HOME_PATH" ]; then
          echo "::notice file=$HOME_PATH::.bashrc exists in the repository."
        else
          echo "::error file=$HOME_PATH::.bashrc does NOT exist in the repository!"
          exit 1 # ファイルがない場合はステップを失敗させる
        fi